---
- hosts: all
  become: true
  tasks:
    - name: Update repository index , install apache package and libapache2-mod-php (ubuntu)
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Update repository index, install httpd package and add php support for httpd(centOS)
      dnf:
        name: 
          - httpd
          - php
        state: latest
        update_cache: yes
      when: ansible_distribution == "CentOS"

